### ISSUE TITLE
F-Droid Release Legit?

### ISSUE THREAD

**Issue by Francewhoa** [miracle2k/android-autostarts#39]
Hello @miracle2k :) Is this f-droid release legit at https://f-droid.org/en/packages/com.elsdoerfer.android.autostarts/
In other words, did you publish this autostarts on F-Droid? Or did someone with Evil behavior did a fake release on F-Droid? I'm asking this for security prevention and before using the F-Droid release.

If this F-Droid release is legit, I suggest updating this "README.md" file at https://github.com/miracle2k/android-autostarts#readme
By adding a URL to https://f-droid.org/en/packages/com.elsdoerfer.android.autostarts/
So that user can validate that this F-Droid release is legit.

@Francewhoa :) This is a note to myself. https://archive.md/bNkSP

**Comment by ildar** [comment]
FYI,
https://github.com/miracle2k/android-autostarts/issues/34#issuecomment-824998112

**Comment by miracle2k** [comment]
It is a community / third party release, which I am thankful for, but can't necessarily vouch for.

**Comment by LeeBinder** [comment]
Hi @miracle2k. How come you don't simply publish a compiled apk on your [releases page](https://github.com/miracle2k/android-autostarts/releases), as does MuntashirAkon on his [releases page](https://github.com/MuntashirAkon/android-autostarts/releases)?

**Comment by miracle2k** [comment]
@LeeBinder No good reason - it would make a lot of sense.

**Comment by LeeBinder** [comment]
Since `apk`s are android **_packages_** and to differentiate them from your source code releases, maybe it would make most sense to supply your compiled apk(s) here at ../[packages](https://github.com/miracle2k?tab=packages&repo_name=android-autostarts) rather than ../[releases](https://github.com/miracle2k/android-autostarts/releases/)?

**Comment by Francewhoa** [comment]
> It is a community / third party release, which I am thankful for, but can't necessarily vouch for.

Thanks for your reply @miracle2k :) Done I contributed both a patch and a pull request at https://github.com/miracle2k/android-autostarts/pull/41

**Comment by Francewhoa** [comment]
@LeeBinder :) Thanks for your contribution and suggestion about the APK

@LeeBinder and @miracle2k :) All my questions in this ticket #39 were answered. As author of this ticket, and to facilitate communications, I'm closing it. As for @LeeBinder's valuable suggestions above, I suggest resuming this discussion in this new ticket at https://github.com/miracle2k/android-autostarts/issues/42
